# ruff: noqa: E501
"""Render the public metrics page from eval history.

Reads ``evals/history/runs.jsonl`` and writes a single self-contained HTML
file to ``docs/metrics/index.html`` — no external CDN, no JS, no CSS
framework. Regenerated by ``make metrics-page`` locally and by the
nightly workflow in CI.

Design language matches the demo UI (system font stack, calm blue
accent, dark mode via ``prefers-color-scheme``). See ADR-0010 §Public
metrics page for the motivation.

Sections rendered:

- Headline card: latest run, gate pass/fail, current production config.
- Ablation table with inline sparklines per metric column.
- Quality-vs-cost scatter: one dot per (strategy, corrective) combo.
- "Impact of corrective RAG" panel — delta per strategy that has both
  corrective on and corrective off runs (references ADR-0007).

The file-level E501 waiver is intentional: HTML/SVG templates
unavoidably have wide f-strings, and forcing breaks makes them less
readable, not more.
"""

from __future__ import annotations

import argparse
import html
import sys
from collections import defaultdict
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path

from rag_harness.evaluation.confidence import (
    bootstrap_ci,
    ci_overlaps_zero,
    paired_diff_ci,
)
from rag_harness.evaluation.history import HistoryEntry, load_history

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_HISTORY_PATH = REPO_ROOT / "evals" / "history" / "runs.jsonl"
DEFAULT_OUTPUT_PATH = REPO_ROOT / "docs" / "metrics" / "index.html"

# Production defaults come from rag_harness.config.Settings. Duplicated
# here so the metrics-page script does not require OPENAI_API_KEY at
# generation time (Settings() would raise without it). If these defaults
# change in config.py, update them here too.
_PROD_STRATEGY = "dense"
_PROD_CORRECTIVE = False

# Every metric column we render in the ablation table. Order matters —
# it drives table layout and the corrective-delta panel. The tuple is
# (HistoryEntry.mean_* field, per_case_scores key, display label).
_QUALITY_METRICS: list[tuple[str, str, str]] = [
    ("mean_context_recall", "context_recall", "Recall"),
    ("mean_context_precision", "context_precision", "Precision"),
    ("mean_faithfulness", "faithfulness", "Faithful"),
    ("mean_correctness", "correctness", "Correct"),
    ("mean_answer_relevancy", "answer_relevancy", "Relevancy"),
]


# --- Data grouping ----------------------------------------------------


def _combo_key(entry: HistoryEntry) -> tuple[str, bool]:
    return (entry.strategy, entry.corrective)


def _group_by_combo(
    entries: list[HistoryEntry],
) -> dict[tuple[str, bool], list[HistoryEntry]]:
    """Group entries by (strategy, corrective), preserving chronological order."""
    groups: dict[tuple[str, bool], list[HistoryEntry]] = defaultdict(list)
    for e in entries:
        groups[_combo_key(e)].append(e)
    return dict(groups)


# --- SVG primitives ---------------------------------------------------


def _sparkline_svg(values: list[float], width: int = 80, height: int = 22) -> str:
    """Return a small inline SVG polyline for the given values.

    Single-point series render as a single dot. Empty or None-only series
    produce an empty SVG (no visible line) so the table cell stays sized.
    """
    cleaned = [v for v in values if v is not None]
    if not cleaned:
        return f'<svg class="spark" width="{width}" height="{height}" viewBox="0 0 {width} {height}"></svg>'

    lo, hi = min(cleaned), max(cleaned)
    span = hi - lo if hi > lo else 1.0
    pad = 2
    n = len(cleaned)
    if n == 1:
        # Center a single dot vertically
        cx = width / 2
        cy = height / 2
        return (
            f'<svg class="spark" width="{width}" height="{height}" viewBox="0 0 {width} {height}">'
            f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="2" fill="currentColor"/>'
            f"</svg>"
        )

    step = (width - 2 * pad) / (n - 1)
    pts = []
    for i, v in enumerate(cleaned):
        x = pad + i * step
        # Higher metric → higher on chart (SVG y grows downward, so invert)
        y = pad + (height - 2 * pad) * (1 - (v - lo) / span)
        pts.append(f"{x:.1f},{y:.1f}")
    last_x, last_y = pts[-1].split(",")
    return (
        f'<svg class="spark" width="{width}" height="{height}" viewBox="0 0 {width} {height}">'
        f'<polyline fill="none" stroke="currentColor" stroke-width="1.4" points="{" ".join(pts)}"/>'
        f'<circle cx="{last_x}" cy="{last_y}" r="1.8" fill="currentColor"/>'
        f"</svg>"
    )


def _scatter_svg(entries: list[HistoryEntry]) -> str:
    """Quality-vs-cost scatter: X = total_cost_usd, Y = mean_correctness.

    Each (strategy, corrective) combo is plotted at its latest values,
    labeled with the strategy name and a suffix ('·c' when corrective is on).
    """
    groups = _group_by_combo(entries)
    if not groups:
        return ""

    latests: list[tuple[str, bool, float, float]] = []
    for (strategy, corrective), rows in groups.items():
        latest = rows[-1]
        latests.append((strategy, corrective, latest.total_cost_usd, latest.mean_correctness))

    xs = [x for _, _, x, _ in latests]
    ys = [y for _, _, _, y in latests]

    # Padding so labels don't clip the edges
    W, H = 620, 260
    ML, MR, MT, MB = 46, 130, 20, 34

    def _rng(vals: list[float]) -> tuple[float, float]:
        lo, hi = min(vals), max(vals)
        if hi == lo:
            return (lo * 0.9 if lo > 0 else 0.0, hi * 1.1 if hi > 0 else 1.0)
        pad = (hi - lo) * 0.12
        return (max(0.0, lo - pad), hi + pad)

    x_lo, x_hi = _rng(xs)
    y_lo, y_hi = _rng(ys)

    def sx(x: float) -> float:
        return ML + (W - ML - MR) * (x - x_lo) / (x_hi - x_lo)

    def sy(y: float) -> float:
        return H - MB - (H - MT - MB) * (y - y_lo) / (y_hi - y_lo)

    axes = (
        f'<line x1="{ML}" y1="{H - MB}" x2="{W - MR}" y2="{H - MB}" '
        f'class="axis"/>'
        f'<line x1="{ML}" y1="{MT}" x2="{ML}" y2="{H - MB}" class="axis"/>'
    )

    # Simple axis ticks — 2 on each axis (min and max) to avoid clutter
    def _tick_x(x: float, label: str) -> str:
        px = sx(x)
        return (
            f'<line x1="{px:.1f}" y1="{H - MB}" x2="{px:.1f}" y2="{H - MB + 4}" class="axis"/>'
            f'<text x="{px:.1f}" y="{H - MB + 16}" class="tick-label tick-x">{html.escape(label)}</text>'
        )

    def _tick_y(y: float, label: str) -> str:
        py = sy(y)
        return (
            f'<line x1="{ML - 4}" y1="{py:.1f}" x2="{ML}" y2="{py:.1f}" class="axis"/>'
            f'<text x="{ML - 6}" y="{py + 4:.1f}" class="tick-label tick-y">{html.escape(label)}</text>'
        )

    ticks = "".join(
        [
            _tick_x(x_lo, f"${x_lo:.4f}"),
            _tick_x(x_hi, f"${x_hi:.4f}"),
            _tick_y(y_lo, f"{y_lo:.2f}"),
            _tick_y(y_hi, f"{y_hi:.2f}"),
        ]
    )

    axis_labels = (
        f'<text x="{(W - MR + ML) / 2:.0f}" y="{H - 4}" class="axis-label">'
        f"Cost per query (USD)</text>"
        f'<text x="14" y="{(H - MB + MT) / 2:.0f}" class="axis-label" '
        f'transform="rotate(-90 14 {(H - MB + MT) / 2:.0f})">Correctness</text>'
    )

    # Ideal (Pareto) direction annotation: up-and-left = better
    guide = f'<text x="{W - MR - 6}" y="{MT + 12}" class="guide-label">↖ better</text>'

    dots = []
    for strategy, corrective, x, y in latests:
        cx = sx(x)
        cy = sy(y)
        label = strategy + (" · corrective" if corrective else "")
        dots.append(
            f'<g class="dot">'
            f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="5" />'
            f'<text x="{cx + 10:.1f}" y="{cy + 4:.1f}" class="dot-label">{html.escape(label)}</text>'
            f"</g>"
        )

    return (
        f'<svg class="scatter" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" '
        f'aria-label="Quality (correctness) vs cost per query, per configuration">'
        f"{axes}{ticks}{axis_labels}{guide}{''.join(dots)}"
        f"</svg>"
    )


# --- Section renderers ------------------------------------------------


def _fmt_cost(v: float) -> str:
    if v == 0:
        return "$0.00"
    if v < 0.001:
        return "< $0.001"
    return f"${v:.4f}"


def _fmt_ms(v: float) -> str:
    if v < 10:
        return f"{v:.1f} ms"
    if v < 1000:
        return f"{int(round(v))} ms"
    return f"{v / 1000:.2f} s"


def _fmt_pct(v: float) -> str:
    return f"{v:.2f}"


def _signed(value: float, fmt: Callable[[float], str]) -> str:
    """Prepend a sign to a formatted delta, but only when the magnitude
    doesn't already start with a comparison-like character (e.g. ``< $0.001``).

    Without this, near-zero deltas render as awkward strings like ``+< $0.001``.
    """
    magnitude = fmt(abs(value))
    if magnitude.startswith("<"):
        return magnitude
    return ("+" if value >= 0 else "−") + magnitude


def _headline_card(entries: list[HistoryEntry]) -> str:
    if not entries:
        return (
            '<section class="card headline"><h2>No runs yet</h2>'
            '<p class="muted">Eval history is empty. Run <code>make eval</code> '
            "to populate it.</p></section>"
        )
    latest = entries[-1]
    gate_status = "passed" if latest.passed else "failed"
    gate_class = "gate-pass" if latest.passed else "gate-fail"
    first_ts = entries[0].timestamp[:10]
    latest_ts = latest.timestamp[:10]

    return (
        f'<section class="card headline">'
        f'<h2>Latest run <span class="{gate_class}">gate {html.escape(gate_status)}</span></h2>'
        f'<dl class="grid">'
        f"<dt>Run date</dt><dd>{html.escape(latest_ts)}</dd>"
        f"<dt>Commit</dt><dd><code>{html.escape(latest.git_commit)}</code></dd>"
        f"<dt>Strategy</dt><dd>{html.escape(latest.strategy)}"
        f"{' · corrective on' if latest.corrective else ''}</dd>"
        f"<dt>Cases</dt><dd>{latest.n_cases}</dd>"
        f"<dt>Production config</dt><dd>{html.escape(_PROD_STRATEGY)}"
        f"{' · corrective on' if _PROD_CORRECTIVE else ' · corrective off'}</dd>"
        f"<dt>History span</dt><dd>{html.escape(first_ts)} → {html.escape(latest_ts)}"
        f" ({len(entries)} runs)</dd>"
        f"</dl></section>"
    )


def _ablation_table(entries: list[HistoryEntry], seed: int | None = None) -> str:
    groups = _group_by_combo(entries)
    if not groups:
        return ""

    # One row per combo, using the latest run's values as the headline
    # numbers and the full historical series as the sparkline.
    rows_data = []
    for combo, rows in groups.items():
        latest = rows[-1]
        history_by_field = {
            mean_field: [getattr(r, mean_field) for r in rows]
            for mean_field, _case_field, _label in _QUALITY_METRICS
        }
        rows_data.append((combo, latest, rows, history_by_field))

    # Sort by latest mean_correctness, descending
    rows_data.sort(key=lambda r: r[1].mean_correctness, reverse=True)

    headers = ["Strategy", "Corrective"]
    for _mean_field, _case_field, label in _QUALITY_METRICS:
        headers.append(label)
    headers += ["p50", "p95", "Cost", "Runs"]

    head_html = "".join(f"<th>{html.escape(h)}</th>" for h in headers)

    body_rows = []
    for (strategy, corrective), latest, rows, hist in rows_data:
        is_prod = strategy == _PROD_STRATEGY and corrective == _PROD_CORRECTIVE
        prod_badge = (
            ' <span class="prod-badge" title="Current production config">prod</span>'
            if is_prod
            else ""
        )
        cells = [
            f"<td>{html.escape(strategy)}{prod_badge}</td>",
            f"<td>{'on' if corrective else 'off'}</td>",
        ]
        for mean_field, case_field, _label in _QUALITY_METRICS:
            val = getattr(latest, mean_field)
            spark = _sparkline_svg(hist[mean_field])
            case_scores = (
                latest.per_case_scores.get(case_field) if latest.per_case_scores else None
            )
            if case_scores:
                lo, hi = bootstrap_ci(case_scores, seed=seed)
                ci_html = f'<span class="ci">[{lo:.2f}–{hi:.2f}]</span>'
            else:
                ci_html = (
                    '<span class="no-ci" title="pre-bootstrap run">(no CI)</span>'
                )
            cells.append(
                f'<td class="num-cell">'
                f'<span class="num">{_fmt_pct(val)}</span> {ci_html}{spark}'
                f"</td>"
            )
        cells.append(f'<td class="num">{_fmt_ms(latest.latency_p50_ms)}</td>')
        cells.append(f'<td class="num">{_fmt_ms(latest.latency_p95_ms)}</td>')
        cells.append(f'<td class="num">{_fmt_cost(latest.total_cost_usd)}</td>')
        cells.append(f'<td class="num">{len(rows)}</td>')
        body_rows.append(f"<tr>{''.join(cells)}</tr>")

    return (
        '<section class="card">'
        "<h2>Ablation table</h2>"
        '<p class="muted">One row per (strategy, corrective) configuration. '
        "Numbers are the latest run; brackets are the 95% bootstrap CI over "
        "per-case scores (see ADR-0011); the inline spark shows historical "
        "trend for that configuration. Rows labeled (no CI) predate "
        "ADR-0011 and do not carry per-case data. Sorted by correctness.</p>"
        '<div class="table-wrap"><table class="ablation">'
        f"<thead><tr>{head_html}</tr></thead>"
        f"<tbody>{''.join(body_rows)}</tbody>"
        "</table></div>"
        "</section>"
    )


def _corrective_delta_panel(entries: list[HistoryEntry], seed: int | None = None) -> str:
    """For each strategy that has both corrective=on and corrective=off, show
    the impact (correctness / cost / latency delta) of the corrective loop.

    References ADR-0007 (corrective RAG) — the panel exists specifically to
    make the tradeoff of that ADR visible on the metrics page.

    Since ADR-0011, when both runs have per-case correctness scores the
    paired-difference CI is computed; if it overlaps zero the delta is
    reported in plain language as not statistically distinguishable from
    zero at the current n. Rows without per-case data are labeled
    "(no CI — pre-bootstrap run)".
    """
    groups = _group_by_combo(entries)

    per_strategy: dict[str, dict[bool, HistoryEntry]] = defaultdict(dict)
    for (strategy, corrective), rows in groups.items():
        per_strategy[strategy][corrective] = rows[-1]

    items = []
    for strategy, by_corrective in per_strategy.items():
        if True not in by_corrective or False not in by_corrective:
            continue
        on = by_corrective[True]
        off = by_corrective[False]
        d_correct = on.mean_correctness - off.mean_correctness
        d_cost = on.total_cost_usd - off.total_cost_usd
        d_p50 = on.latency_p50_ms - off.latency_p50_ms

        pp = f"{d_correct * 100:+.1f}pp"
        cost = _signed(d_cost, _fmt_cost)
        latency = _signed(d_p50, _fmt_ms)

        # Try to compute a paired-difference CI on correctness. Both sides
        # need per-case data and matching case counts.
        on_scores = on.per_case_scores.get("correctness") if on.per_case_scores else None
        off_scores = off.per_case_scores.get("correctness") if off.per_case_scores else None
        have_ci = bool(on_scores and off_scores and len(on_scores) == len(off_scores))

        strategy_html = f'<span class="strategy-name">{html.escape(strategy)}</span>'
        cost_html = f'<span class="delta">{html.escape(cost)}</span> cost'
        latency_html = f'<span class="delta">{html.escape(latency)}</span> p50 latency'

        if have_ci:
            assert on_scores is not None and off_scores is not None  # narrow for mypy
            ci = paired_diff_ci(on_scores, off_scores, seed=seed)
            n = len(on_scores)
            if ci_overlaps_zero(ci):
                # Sign is a coin flip at this n. Say so in plain language.
                items.append(
                    f"<li>{strategy_html}: "
                    f'<span class="delta indeterminate-delta">{html.escape(pp)}</span>'
                    f' correctness &mdash; <em class="ci-note">this difference is '
                    f"not statistically distinguishable from zero at n={n}.</em> "
                    f"{cost_html} &middot; {latency_html}</li>"
                )
            else:
                # Genuine effect. Colour it and show the CI.
                correct_class = (
                    "delta correct-delta" if d_correct >= 0 else "delta regress-delta"
                )
                lo_pp = f"{ci[0] * 100:+.1f}pp"
                hi_pp = f"{ci[1] * 100:+.1f}pp"
                items.append(
                    f"<li>{strategy_html}: "
                    f'<span class="{correct_class}">{html.escape(pp)}</span> correctness '
                    f'<span class="ci">[{html.escape(lo_pp)}, {html.escape(hi_pp)}]</span>'
                    f" &middot; {cost_html} &middot; {latency_html}</li>"
                )
        else:
            # No per-case data on at least one side. Colour by sign but
            # label the CI gap explicitly so mixed-history pages read as
            # data-provenance, not a bug.
            correct_class = (
                "delta correct-delta" if d_correct >= 0 else "delta regress-delta"
            )
            items.append(
                f"<li>{strategy_html}: "
                f'<span class="{correct_class}">{html.escape(pp)}</span>'
                f' correctness &mdash; <em class="ci-note">(no CI &mdash; '
                f"pre-bootstrap run).</em> {cost_html} &middot; {latency_html}</li>"
            )

    if not items:
        return ""

    return (
        '<section class="card">'
        "<h2>Impact of corrective RAG</h2>"
        '<p class="muted">Delta of the corrective loop (ADR-0007), '
        "per strategy that has both corrective on and off runs. Positive "
        "correctness is better; positive cost and latency are worse.</p>"
        f'<ul class="corrective-list">{"".join(items)}</ul>'
        "</section>"
    )


def _scatter_section(entries: list[HistoryEntry]) -> str:
    svg = _scatter_svg(entries)
    if not svg:
        return ""
    return (
        '<section class="card">'
        "<h2>Quality vs cost</h2>"
        '<p class="muted">Each dot is a configuration at its latest values. '
        "Up and to the left is better: more correct answers at lower cost per query.</p>"
        f"{svg}"
        "</section>"
    )


# --- Page assembly ----------------------------------------------------


_STYLE = """
:root {
  --font-sans: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  --font-mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
  --bg: #ffffff;
  --bg-muted: #f7fafc;
  --border: #e2e8f0;
  --text: #1a202c;
  --text-muted: #4a5568;
  --accent: #2b6cb0;
  --pass: #2f855a;
  --fail: #c53030;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1a202c;
    --bg-muted: #2d3748;
    --border: #2d3748;
    --text: #f7fafc;
    --text-muted: #a0aec0;
    --accent: #63b3ed;
    --pass: #68d391;
    --fail: #fc8181;
  }
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; background: var(--bg); color: var(--text); font-family: var(--font-sans); font-size: 15px; line-height: 1.55; -webkit-font-smoothing: antialiased; }
.page { max-width: 960px; margin: 0 auto; padding: 2.5rem 1.25rem 4rem; }
h1 { font-size: 1.6rem; font-weight: 600; letter-spacing: -0.015em; margin: 0 0 0.35rem; }
h2 { font-size: 1rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: var(--text-muted); margin: 0 0 0.9rem; }
.tagline { color: var(--text-muted); margin: 0 0 2rem; }
.card { padding: 1.15rem 1.35rem; border: 1px solid var(--border); border-radius: 8px; background: var(--bg); margin-bottom: 1.5rem; }
.headline .grid { display: grid; grid-template-columns: max-content 1fr; gap: 0.35rem 1.5rem; margin: 0; }
.headline dt { font-size: 0.82rem; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.05em; }
.headline dd { margin: 0; font-family: var(--font-mono); font-size: 0.9rem; }
.gate-pass { color: var(--pass); font-size: 0.85rem; font-weight: 500; margin-left: 0.4rem; text-transform: none; letter-spacing: 0; }
.gate-fail { color: var(--fail); font-size: 0.85rem; font-weight: 500; margin-left: 0.4rem; text-transform: none; letter-spacing: 0; }
.muted { color: var(--text-muted); font-size: 0.88rem; margin: 0 0 0.85rem; }
.table-wrap { overflow-x: auto; }
table.ablation { border-collapse: collapse; width: 100%; font-size: 0.85rem; font-family: var(--font-mono); }
table.ablation th, table.ablation td { padding: 0.5rem 0.6rem; border-bottom: 1px solid var(--border); text-align: left; }
table.ablation th { font-family: var(--font-sans); font-weight: 500; color: var(--text-muted); text-transform: none; letter-spacing: 0; font-size: 0.82rem; }
table.ablation td.num { text-align: right; color: var(--text-muted); }
table.ablation td.num-cell { text-align: right; white-space: nowrap; }
table.ablation td.num-cell .num { margin-right: 0.4rem; }
table.ablation svg.spark { color: var(--accent); vertical-align: middle; }
.prod-badge { background: var(--accent); color: white; font-size: 0.7rem; padding: 0.05rem 0.35rem; border-radius: 3px; margin-left: 0.35rem; font-family: var(--font-sans); text-transform: uppercase; letter-spacing: 0.05em; }
svg.scatter { display: block; margin: 0 auto; color: var(--accent); }
svg.scatter .axis { stroke: var(--border); stroke-width: 1; }
svg.scatter .tick-label { fill: var(--text-muted); font-size: 10px; font-family: var(--font-mono); }
svg.scatter .tick-x { text-anchor: middle; }
svg.scatter .tick-y { text-anchor: end; }
svg.scatter .axis-label { fill: var(--text-muted); font-size: 11px; font-family: var(--font-sans); text-anchor: middle; }
svg.scatter .guide-label { fill: var(--text-muted); font-size: 10px; font-family: var(--font-sans); text-anchor: end; }
svg.scatter .dot circle { fill: var(--accent); stroke: var(--bg); stroke-width: 2; }
svg.scatter .dot-label { fill: var(--text); font-size: 11px; font-family: var(--font-mono); dominant-baseline: middle; }
ul.corrective-list { list-style: none; padding: 0; margin: 0; font-family: var(--font-mono); font-size: 0.88rem; }
ul.corrective-list li { padding: 0.35rem 0; border-bottom: 1px solid var(--border); }
ul.corrective-list li:last-child { border-bottom: none; }
.strategy-name { color: var(--text); }
.delta { color: var(--text-muted); }
.correct-delta { color: var(--pass); }
.regress-delta { color: var(--fail); }
.indeterminate-delta { color: var(--text-muted); font-weight: 500; }
.ci { color: var(--text-muted); font-size: 0.9em; }
.no-ci { color: var(--text-muted); font-size: 0.85em; font-style: italic; }
.ci-note { color: var(--text-muted); font-style: italic; }
footer.site-footer { color: var(--text-muted); font-size: 0.82rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); font-family: var(--font-mono); }
code { font-family: var(--font-mono); font-size: 0.85em; background: var(--bg-muted); padding: 0.05em 0.35em; border-radius: 3px; }
"""


def render_page(
    entries: list[HistoryEntry],
    generated_at: datetime,
    source_path: str = "evals/history/runs.jsonl",
    seed: int | None = None,
) -> str:
    """Return the full HTML for the metrics page.

    ``seed`` is passed through to the bootstrap-CI computations so tests
    can pin the output deterministically. Production callers leave it
    ``None`` — at 1000 iterations the CIs are already stable to two
    decimals across seeds.
    """
    ts_str = generated_at.strftime("%Y-%m-%d %H:%M UTC")

    if not entries:
        body = _headline_card(entries)
    else:
        body = (
            _headline_card(entries)
            + _ablation_table(entries, seed=seed)
            + _scatter_section(entries)
            + _corrective_delta_panel(entries, seed=seed)
        )

    footer = (
        '<footer class="site-footer">'
        f"Generated {html.escape(ts_str)} from {len(entries)} eval "
        f"{'run' if len(entries) == 1 else 'runs'}. "
        f"Source: <code>{html.escape(source_path)}</code>."
        "</footer>"
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RAG harness — evaluation metrics</title>
<meta name="description" content="Eval history and ablation results for the RAG harness (reliability-first RAG over pinned Kubernetes docs).">
<meta name="robots" content="noindex,nofollow">
<style>{_STYLE}</style>
</head>
<body>
<main class="page">
<header>
<h1>RAG harness — evaluation metrics</h1>
<p class="tagline">History of every eval and ablation run, kept in the repo at <code>{html.escape(source_path)}</code>. Regenerated by CI on every nightly eval and on every release.</p>
</header>
{body}
{footer}
</main>
</body>
</html>
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render the public metrics page.")
    parser.add_argument(
        "--history",
        type=Path,
        default=DEFAULT_HISTORY_PATH,
        help="Path to the eval history JSONL. Defaults to evals/history/runs.jsonl.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Output path for the rendered HTML. Defaults to docs/metrics/index.html.",
    )
    args = parser.parse_args(argv)

    entries = load_history(args.history)
    now = datetime.now(UTC)
    html_str = render_page(entries, now)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(html_str, encoding="utf-8")
    # Prefer a repo-relative display path; fall back to absolute when the
    # output lives outside the repo (e.g. under a test's tmp_path).
    try:
        display = args.out.relative_to(REPO_ROOT)
    except ValueError:
        display = args.out
    print(f"wrote {display} ({len(entries)} runs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
